### ISSUE TITLE
Update to 1.20.4

### ISSUE THREAD

**Issue by HadrianFinch** [cph101/Lodestonelib-fabric#2]
Hello, 1.20.4 has been out for quite some time now and I was wondering if this library will have an update. I know that Trip1e has made a [fork of this library for 1.20.4](https://github.com/Tripp1e/Lodestonelib-fabric-1.20.4), but that doesn't seem to work for me.

**Comment by cph101** [comment]
Updating for 1.20.4 is indeed on the agenda. However, I’m unfortunately quite busy right now, so I can’t guarantee a time as of now.

**Comment by HadrianFinch** [comment]
Fantastic! No worries, get to It when you can. I will happily await the update whenever it comes.
